### PR TITLE
Adding profile component

### PR DESCRIPTION
**Pull request by Alzhan-B**

### CODE REVIEW

**Comment by mojahmed** [comment]
code the dream and 5 more pages - Personal - Microsoft​ Edge 12_27_2024 9_09_41 PM
looks good thank you alzhan

**Review by tianahR — COMMENTED** [review]
Looks good

**Review by vitaliipp — APPROVED** [review]
Good job!

**Comment by Alzhan-B** [comment]
image

**Comment by mojahmed** [comment]
looks good the new update , if we finish everything important before January 15 and we still have time we can implement bio field in this card bec its already exist in our back-end code but for now everything looks good , thank you

**Review by mojahmed — APPROVED** [review]

**Pull request merged**
