### PR TITLE
Murat create post card and post list

### PR DESCRIPTION
**Pull request by muratsimsk**
Added PostList and PostCard components. Each post in PostList is displayed using PostCard component which contains post title, date, subtitle and an image. It is still a design, no backend functions are implemented.

Ekran Resmi 2024-12-19 ÖÖ 2 01 43

### CODE REVIEW

**Comment by AnnaViktorovna** [comment]
Murat, for me it's look like a home page

**Review by AnnaViktorovna — APPROVED** [review]

**Review by vitaliipp — APPROVED** [review]
Good job!

**Review by tianahR — APPROVED** [review]
Approved

**Comment by mojahmed** [comment]
Great job
One thing to think about is making the view count persistent—it currently resets on reload. We could add a back-end controller for that, or if you prefer, we can show the author's name instead since Faratiana already implemented the author controller

**Comment by muratsimsk** [comment]
> Great job One thing to think about is making the view count persistent—it currently resets on reload. We could add a back-end controller for that, or if you prefer, we can show the author's name instead since Faratiana already implemented the author controller

Its good idea to show author's name instead view count.

**Pull request merged**
