### PR TITLE
footer was added

### PR DESCRIPTION
**Pull request by AnnaViktorovna**
any suggestion, please.
And I don't know if we really need link to policy

### CODE REVIEW

**Comment by muratsimsk** [comment]
The code and links look good. I don't think there is any need for the " Logo and
Welcome to the CTD Practicum Blog App" part.

**Comment by AnnaViktorovna** [comment]
> The code and links look good. I don't think there is any need for the " Logo and Welcome to the CTD Practicum Blog App" part.

Maybe Welcome to the CTD Practicum Blog App we don't need, but the school website has logo on the footer

**Review by vitaliipp — APPROVED** [review]
Looks good to me. Please make sure to add a screenshot and description next time.

**Review by tianahR — APPROVED** [review]
Approve

**Pull request merged**
